Update threatspec.yml

diff --git a/.github/workflows/threatspec.yml b/.github/workflows/threatspec.yml
--- a/.github/workflows/threatspec.yml
+++ b/.github/workflows/threatspec.yml
@@ -17,6 +17,15 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
+      - name: Check for specific file
+        run: |
+          if [[ $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}) =~ ".github/threatmodel/threatmodel" ]]; then
+            echo "Specific file found. Starting build..."
+          else
+            echo "Specific file not found. Skipping build."
+            exit 78
+          fi
+        
       - name: Run a multi-line script
         run: |
           git clone https://github.com/threatspec/threatspec.git
